name: 'scout_engine'
version: '1.0.0'
config-version: 2
profile: portfolio

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  scout_engine:
    staging:
      +materialized: view
    marts:
      +materialized: table
